config/routes.rb
Rails.application.routes.draw do
  #sets the default routing
  root 'books#index'
  
  
  get 'books/index'
  get 'books/AddBook'
  get 'books/UpdateBook'
  get 'books/ShowDetails'
  get 'books/Delete'
  
  
  resources :books do
    member do
      get :delete
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all.each
  end

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def show
    @book = Book.find(params[:id])
  end

  def delete
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book created successfully"
      redirect_to(books_path)  
    else
      render('new')
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(book_params)
      flash[:notice] = "Book updated successfully"
      redirect_to(books_path)
    else
      render('edit')
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book '#{@book.title}' destroyed successfully"
    redirect_to(books_path)
  end 
    
  def book_params
    params.require(:book).permit(:title, :author,:genre, :price, :published_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/control_helper.rb
module ControlHelper
end

app/views/books/delete.html.erb
<%= link_to("<< Back to List", :action => 'index') %>

<h1>Delete Book</h1>
<%= form_for(@book, :method => 'delete') do |f| %>
    <p> Are you sure you want to permanently delete this book? </p>
    <p> <%= f.object.title %> </p>
    <%= f.submit("Delete Book") %>
<% end %>

app/views/books/edit.html.erb
<%= link_to("<< Back to List", :action => 'index') %>

<h1>Update Book</h1>

<%= form_for(@book) do |f| %>
    <table summary= "Book Form Fields">
        <tr>
            <th>Title</th>
            <td><%= f.text_field(:title) %></td>
        </tr>
        <tr>
            <th>Author</th>
            <td><%= f.text_field(:author) %></td>
        </tr>
        <tr>
            <th>Genre</th>
            <td> <%= f.select :genre, ['Fantasy','Science Fiction','Young Adult','Romance','Childrens','Horror', 'Mystery','NonFiction','Thriller','Adventure','Biography','Autobiography'] %></td>
        </tr>
        <tr>
            <th>Price</th>
            <td><%= f.number_field :price, step: :any %></td>
        </tr>
        <tr>
            <th>Published Date</th>
            <td> <%= f.date_select :published_date, start_year: Time.new(1600).year, end_year: Time.now.year %> </td> 
        </tr>
    </table>

    <%= f.submit("Update Book") %>
<% end %>

app/views/books/index.html.erb
<% if !flash[:notice].blank? %>
    <%= flash[:notice] %>
<%end%>

<h1>Books Homepage</h1>
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
</style>

<%= link_to("Add New Book", new_book_path, :action => 'new') %>

<h2> Books </h2>
<p> Bellow includes of the books added </p>
<table style="width:100%">
    <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Genre</th>
        <th>Price</th>
        <th>Published Date</th>
        <th>Actions</th>
    </tr>
    <%for x in @books%>
        <tr >
            <td><%= x.title%></td>
            <td><%= x.author%></td>
            <td><%= x.genre%></td>
            <td><%= x.price%></td>
            <td><%= x.published_date.strftime("%Y-%m-%d")%>
            <td class = "actions">
                <%= link_to("Show Details",book_path(x), :class => 'action show')%>
                <%= link_to("Edit Book", edit_book_path(x), :class => 'action edit')%>
                <%= link_to("Delete Book", delete_book_path(x), :class => 'action delete')%>
            </td>    
        </tr>
    <%end%>
</table> 

app/views/books/new.html.erb
<% if !flash[:notice].blank? %>
    <%= flash[:notice] %>
<%end%>

<%= link_to("<< Back to List", :action => 'index') %>

<h1>Add Book</h1>
<p>Enter info to add a new book to the main page</p>


<%= form_for (@book) do |f| %>
    <%= f.label :title%> <br />
    <%= f.text_field(:title) %> <br />
    <%= f.label :author%> <br />
    <%= f.text_field(:author) %><br />
    <%= f.label :genre%> <br />
    <%= f.select :genre, ['Fantasy','Science Fiction','Young Adult','Romance','Childrens','Horror', 'Mystery','NonFiction','Thriller','Adventure','Biography','Autobiography'] %><br />
    <%= f.label :price%> <br />
    <%= f.number_field :price, step: :any %><br />
    <%= f.label :published_date%> <br />
    <%= f.date_select :published_date, start_year: Time.new(1600).year, end_year: Time.now.year %>
    <%#= f.select :published_date, ((1800..Date.current.year.to_i).to_a.reverse)%><br /><br />
    <%=f.submit("Add Book")%><br />
<% end %>

app/views/books/show.html.erb
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
</style>

<%= link_to("<< Back to List", :action => 'index') %>

<h2> Show Details </h2>
<table summary="Book Detail View">
    <tr>
        <th>Title</th>
        <td><%= @book.title %></td>
    </tr>
    <tr>
        <th>Author</th>
        <td><%= @book.author %></td>
    </tr>
    <tr>
        <th>Genre</th>
        <td><%= @book.genre %></td>
    </tr>
    <tr>
        <th>Price</th>
        <td><%= @book.price %></td>
    </tr>
    <tr>
        <th>Published Date</th>
        <td><%= @book.published_date.strftime("%Y-%m-%d") %></td>
    </tr>
    <tr>
        <th>Created</th>
        <td><%= @book.created_at %></td>
    </tr>
    <tr>
        <th>Updated</th>
        <td><%= @book.updated_at %></td>
    </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>